"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbars from "@/component/Navbars";
import { Provider } from "react-redux";
import { store } from "../store/store";
import SessionWrapper from "@/component/SessionWraper";
import { useState } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
const [Open, setOpen] = useState("light");
  return (
    <html lang="en">
      <body
           
        className={ `${Open=="dark"?"bg-gray-800 text-blue-50":"bg-white text-black"}  ${geistSans.variable} ${geistMono.variable} antialiased   `}
      > <SessionWrapper>  <Navbars opens={Open} setOpens={setOpen} />
     <Provider store={store}>{children}</Provider></SessionWrapper>
        
      </body>
    </html>
  );
}
